name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      run: "ruby -v && sudo gem install jekyll bundler && bundle exec jekyll build -d _site/"
